"""Spreads trading engine boundaries."""

from .capture_targets import refresh_engine_capture_targets
from .data_runtime import DataEngine
from .entry_quality import (
    ENTRY_QUALITY_PROFILE_REGISTRY,
    MOMENTUM_LONG_CALL_PROFILE_ID,
    MOMENTUM_LONG_CALL_V1,
    OPTION_STRUCTURE_PROFILE_IDS,
    OPTION_STRUCTURE_PROFILES,
    EntryFilter,
    EntryFilterRef,
    EntryQualityContext,
    EntryQualityProfile,
    EntryQualityStage,
    EntryQualityStageName,
    EntryQualityStatus,
    EntryQualityWaterfall,
    FeatureSnapshot,
    FilterResult,
    FilterResultStatus,
    list_entry_quality_profiles,
    resolve_entry_quality_profile,
)
from .entry_quality_evidence import EntryQualityAnalysis, build_entry_quality_analysis
from .entry_quality_pipeline import (
    POST_SELECTION_ENTRY_QUALITY_STAGES,
    PRE_SELECTION_ENTRY_QUALITY_STAGES,
    evaluate_entry_quality_snapshot,
    evaluate_momentum_long_call_snapshot,
)
from .entry_selection import EntrySelectionEngine, EntrySelectionResult
from .feature_snapshots import (
    FEATURE_SNAPSHOT_BUILDER_REGISTRY,
    FeatureSnapshotBuilder,
    FeatureSnapshotBuilderKey,
    build_feature_snapshots_for_strategy,
    build_momentum_long_call_feature_snapshots,
    register_feature_snapshot_builder,
    resolve_feature_snapshot_builder,
)
from .exit_runtime import ExitEngine
from .kernel import EngineComponentRole, EngineContext, EngineRunRef
from .market_context import (
    MarketBenchmarkEvidence,
    MarketBenchmarkRole,
    MarketContextDataQuality,
    MarketContextDataQualityState,
    MarketContextFidelityLabel,
    MarketContextFreshnessState,
    MarketContextSnapshot,
    MarketRegimeLabel,
    MarketRiskPosture,
    MarketTrendStrength,
    MarketVolatilityState,
    RegimeSnapshot,
)
from .portfolio_runtime import PortfolioEngine

__all__ = [
    "DataEngine",
    "ENTRY_QUALITY_PROFILE_REGISTRY",
    "EngineComponentRole",
    "EngineContext",
    "EngineRunRef",
    "EntryQualityAnalysis",
    "EntryFilter",
    "EntryFilterRef",
    "EntryQualityContext",
    "EntryQualityProfile",
    "EntryQualityStage",
    "EntryQualityStageName",
    "EntryQualityStatus",
    "EntryQualityWaterfall",
    "EntrySelectionEngine",
    "EntrySelectionResult",
    "FEATURE_SNAPSHOT_BUILDER_REGISTRY",
    "FeatureSnapshot",
    "FeatureSnapshotBuilder",
    "FeatureSnapshotBuilderKey",
    "FilterResult",
    "FilterResultStatus",
    "MarketBenchmarkEvidence",
    "MarketBenchmarkRole",
    "MarketContextDataQuality",
    "MarketContextDataQualityState",
    "MarketContextFidelityLabel",
    "MarketContextFreshnessState",
    "MarketContextSnapshot",
    "MarketRegimeLabel",
    "MarketRiskPosture",
    "MarketTrendStrength",
    "MarketVolatilityState",
    "MOMENTUM_LONG_CALL_PROFILE_ID",
    "MOMENTUM_LONG_CALL_V1",
    "OPTION_STRUCTURE_PROFILE_IDS",
    "OPTION_STRUCTURE_PROFILES",
    "POST_SELECTION_ENTRY_QUALITY_STAGES",
    "PRE_SELECTION_ENTRY_QUALITY_STAGES",
    "PortfolioEngine",
    "RegimeSnapshot",
    "ExitEngine",
    "build_entry_quality_analysis",
    "build_feature_snapshots_for_strategy",
    "build_momentum_long_call_feature_snapshots",
    "evaluate_entry_quality_snapshot",
    "evaluate_momentum_long_call_snapshot",
    "list_entry_quality_profiles",
    "register_feature_snapshot_builder",
    "refresh_engine_capture_targets",
    "resolve_feature_snapshot_builder",
    "resolve_entry_quality_profile",
]
